name: foodpanda_clone
description: A food delivery app using GetX
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.7.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  logger: ^2.6.2
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  flutter_stripe: ^11.0.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_chat_ui: ^1.6.12
  flutter_chat_types: ^3.6.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.1.0
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
