name: foodpanda
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.7.0
  intl: ^0.20.2
  logger: ^2.6.2
  google_maps_flutter: ^2.10.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_polyline_points: ^3.1.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  awesome_notifications: ^0.10.1
  permission_handler: ^12.0.1
  flutter_stripe: ^12.1.1
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^7.2.0
  flutter_chat_ui: ^2.11.1
  flutter_chat_types: ^3.6.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^4.0.3
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^7.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
